import { useState } from 'react'

const translations = {
  en: {
    navCta: 'Join Waitlist',
    heroBadge: 'Free for Indians · Launching 2025',
    heroTitle: ['Stop Losing Track', 'of Your'],
    heroAccent: 'Paisa',
    heroSub: 'All your UPI transactions — GPay, PhonePe, Paytm, CRED — in one place, in plain language. No spreadsheets. Just clarity.',
    heroBtn: 'Join Free Waitlist →',
    heroInput: 'Enter your email',
    waitlistPeople: 'people already on the waitlist',
    successMsg: "✓ You're on the list! We'll notify you at launch.",
    problemLabel: 'THE PROBLEM',
    problemTitle: "Your money is a mystery.\nIt shouldn't be.",
    problemSub: "You earn well. You work hard. But at the end of the month, you genuinely don't know where it all went.",
    calcLabel: 'MONEY LEAK CALCULATOR',
    calcTitle: 'How much are you leaking every month?',
    calcIncome: 'Monthly Income',
    calcApps: 'Payment apps you use',
    calcChecks: 'Times you check balance daily',
    calcResultLabel: "estimated monthly spending you can't account for",
    quizLabel: 'MONEY PERSONALITY QUIZ',
    quizTitle: "What's your money type?",
    quizSkip: 'skip',
    quizNext: 'Next →',
    quizJoin: "Join Waitlist — It's Free →",
    quizRestart: 'Take quiz again',
    howLabel: 'HOW IT WORKS',
    howTitle: 'Clarity in 3 steps',
    shareLabel: 'TELL YOUR FRIENDS',
    shareTitle: 'Skip the queue. Bring a friend.',
    shareSub: 'Every friend you refer moves you 10 spots up the waitlist.',
    shareWA: 'Share on WhatsApp',
    shareTW: 'Tweet this',
    shareLI: 'Share on LinkedIn',
    refLabel: 'Your referral code',
    refCopy: 'Copy Code',
    refSub: 'Share this code with friends. When they join, you both move up the list!',
    finalTitle: ['Your money deserves', ''],
    finalAccent: 'clarity',
    finalSub: 'Join 1,247 Indians who are done with the guessing game.',
    finalBtn: 'Get Early Access →',
    finalMeta: 'Free forever · No spam · No passwords stored · RBI compliant',
  },
  hi: {
    navCta: 'वेटलिस्ट जॉइन करें',
    heroBadge: 'भारतीयों के लिए मुफ़्त · 2025 में लॉन्च',
    heroTitle: ['अपने पैसे पर नज़र', 'रखना शुरू करें'],
    heroAccent: '',
    heroSub: 'GPay, PhonePe, Paytm, CRED — सभी UPI लेन-देन एक जगह, सरल भाषा में। कोई स्प्रेडशीट नहीं।',
    heroBtn: 'मुफ़्त वेटलिस्ट जॉइन करें →',
    heroInput: 'ईमेल दर्ज करें',
    waitlistPeople: 'लोग पहले से वेटलिस्ट पर हैं',
    successMsg: '✓ आप लिस्ट में हैं! लॉन्च पर नोटिफ़िकेशन मिलेगा।',
    problemLabel: 'समस्या',
    problemTitle: 'आपका पैसा एक रहस्य है।\nयह नहीं होना चाहिए।',
    problemSub: 'आप अच्छा कमाते हैं। मेहनत करते हैं। लेकिन महीने के अंत में नहीं जानते पैसा कहाँ गया।',
    calcLabel: 'मनी लीक कैलकुलेटर',
    calcTitle: 'हर महीने आपके कितने पैसे लीक हो रहे हैं?',
    calcIncome: 'मासिक आय',
    calcApps: 'आप कितने ऐप्स उपयोग करते हैं',
    calcChecks: 'रोज़ बैलेंस चेक करना',
    calcResultLabel: 'अनुमानित मासिक खर्च जिसका हिसाब नहीं',
    quizLabel: 'मनी पर्सनालिटी क्विज़',
    quizTitle: 'आपका money type क्या है?',
    quizSkip: 'छोड़ें',
    quizNext: 'अगला →',
    quizJoin: 'वेटलिस्ट जॉइन करें — मुफ़्त →',
    quizRestart: 'क्विज़ दोबारा लें',
    howLabel: 'कैसे काम करता है',
    howTitle: '3 चरणों में स्पष्टता',
    shareLabel: 'दोस्तों को बताएं',
    shareTitle: 'लाइन छोड़ो। दोस्त को बुलाओ।',
    shareSub: 'हर रेफ़रल से आप 10 स्थान ऊपर जाते हैं।',
    shareWA: 'WhatsApp पर शेयर करें',
    shareTW: 'Tweet करें',
    shareLI: 'LinkedIn पर शेयर करें',
    refLabel: 'आपका रेफ़रल कोड',
    refCopy: 'कोड कॉपी करें',
    refSub: 'यह कोड दोस्तों के साथ शेयर करें। जब वे जुड़ेंगे, आप दोनों आगे बढ़ेंगे!',
    finalTitle: ['आपके पैसे को', ''],
    finalAccent: 'स्पष्टता चाहिए',
    finalSub: '1,247 भारतीयों से जुड़ें जो अनुमान लगाना बंद कर रहे हैं।',
    finalBtn: 'अर्ली एक्सेस पाएं →',
    finalMeta: 'हमेशा मुफ़्त · कोई स्पैम नहीं · RBI अनुपालित',
  }
}

export function useLang() {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  const toggleLang = () => setLang(l => l === 'en' ? 'hi' : 'en')
  return { lang, t, toggleLang }
}
